squashed bugs, see coments in prior commit of file

diff --git a/bin/wm b/bin/wm
--- a/bin/wm
+++ b/bin/wm
@@ -1,35 +1,18 @@
 #!/bin/bash
 #
-# Change .xinitrc and startx
-# Treats first arg as the * in *.xinitrc
-# Treats second arg as display number
-# Symlinks .xinitrc
-# Starts X on requested display
-#
-#
-# BUGS
-#
-# * Should fail if $2 isn't a number
-# * Should fail if $1.xinitrc doesn't exist
-#   (The `ls` with colour should at least warn about this)
+# Eats file from xinitrc.d
+# Shits symlink to file from xinitrc.d
+# Eats display number
+# Shits xsession
 #
 
-#if [ -z $1 ]; then
-#    echo "No argument. Leaving .xinitrc alone."
-#    exit 0
-#fi
-
-[ -z $1 ] && echo "No argument. Leaving .xinitrc alone." && exit 0
-
-rm ~/.xinitrc
-"ln" -s ~/.xinitrc.d/$1.xinitrc ~/.xinitrc
-"ls" --color=auto -l ~/.xinitrc
-
-[ -z $2 ] && echo "No display chosen. Not starting X." && exit 1
-
-#if [ -z $2 ]; then
-#    echo "No display chosen. Not starting X."
-#    exit 1
-#fi
-
-startx -- :$2
+xinits_path="$HOME/.config/xinitrc.d"
+[ -z $1 ] && echo "usage: wm <xinitrc> <display number>" && exit 0
+if [ -e "$xinits_path/$1.xinitrc" ]; then
+    rm ~/.xinitrc
+    "ln" -s "$xinits_path/$1.xinitrc" "$HOME/.xinitrc"
+    #"file" "$HOME/.xinitrc"
+else echo "Not found: $xinits_path/$1.xinitrc" && exit 1
+fi
+[ -z $2 ] && exit 0
+[ $2 -gt 0 ] && startx -- :$2 || exit 1
